# Generated by Django 6.0.3 on 2026-04-02 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Wake Up!', max_length=100)),
                ('time', models.TimeField()),
                ('days', models.JSONField(default=list, help_text='List of weekday ints 0=Mon..6=Sun')),
                ('is_active', models.BooleanField(default=True)),
                ('snooze_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('kitchen', 'Kitchen'), ('decor', 'Decor'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('hint', models.CharField(help_text='Hint shown to user when challened', max_length=200)),
                ('emoji', models.CharField(default='📦', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('triggered', 'Triggered'), ('solved', 'Solved'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=500)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_detected_label', models.CharField(blank=True, max_length=200)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='alarm_app.alarm')),
                ('assigned_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alarm_app.roomobjects')),
            ],
        ),
    ]
